name: Static Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pandas type stubs
        run: pip install pandas-stubs
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black mypy numpy opencv-python pillow scipy pandas
          pip install types-pillow

      - name: Run flake8 (Linting)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run black (Auto-Fix Formatting)
        run: black .

      - name: Run mypy (Type Checking)
        run: |
          # Check if mypy.ini is present in the repo, and if so, run mypy with it
          if [ -f mypy.ini ]; then
            mypy --show-traceback --ignore-missing-imports --config-file mypy.ini .
          else
            mypy --show-traceback --ignore-missing-imports .
          fi
